#! /bin/sh

# TODO: upgrade to 9.10; released literally 15 minutes ago (mirror syncs)

name=coreutils
version=9.9
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/coreutils/coreutils-${version}.tar.xz"
tarball_blake2b="ddae0c1ff882739712e901d6eb1373e4172de9335b95b4c1004773aadc6b7e3cb3bf5aa583f13034062a75dc9194bf8534b0f7f1258c8ff64595b1301964e124"
hostdeps="${OS_TCDEP} pkg-config"
deps="core-libs"

prepare() {
	autotools_recursive_regen
}

configure() {
		EXTRA_CFLAGS="-DSLOW_BUT_NO_HACKS" \
	autotools_configure \
		--enable-no-install-program="mkfifo,runcon,chroot,uptime"
}

build() {
	make -j${parallelism}
}

package() {
	make install DESTDIR="${dest_dir}"

	post_package_strip
}
