#! /bin/sh

name=fastfetch
version=2.59.0
revision=1
git_url="https://github.com/fastfetch-cli/fastfetch.git"
commit="aa3a916d5a455f95405f68d0e22463ec3f517991"
hostdeps="${OS_TCDEP} pkg-config"
deps="core-libs"

configure() {
	cmake_configure \
    		-DENABLE_RPM=no \
    		-DENABLE_ZLIB=no \
    		-DENABLE_SYSTEM_YYJSON=no \
    		-DINSTALL_LICENSE=no \
    		-DBUILD_FLASHFETCH=no \
    		-DENABLE_CHAFA=no \
    		-DENABLE_DBUS=no \
    		-DENABLE_DCONF=no \
    		-DENABLE_DDCUTIL=no \
    		-DENABLE_DRM=no \
    		-DENABLE_ELF=no \
    		-DENABLE_EGL=no \
    		-DENABLE_GIO=no \
    		-DENABLE_GLX=no \
    		-DENABLE_IMAGEMAGICK6=no \
    		-DENABLE_IMAGEMAGICK7=no \
    		-DENABLE_OPENCL=no \
    		-DENABLE_OSMESA=no \
    		-DENABLE_PULSE=no \
    		-DENABLE_SQLITE3=no \
    		-DENABLE_VULKAN=no \
    		-DENABLE_WAYLAND=no \
    		-DENABLE_XCB_RANDR=no \
    		-DENABLE_XFCONF=no \
    		-DENABLE_XRANDR=no \
    		-DBUILD_TESTS=no
}

build() {
	cmake --build . -j${parallelism}
}

package() {
	DESTDIR="${dest_dir}" cmake --install .

	post_package_strip
}
