#! /bin/sh

name=findutils
version=4.10.0
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/findutils/findutils-${version}.tar.xz"
tarball_blake2b="2eebdcb425c04170d17afb80e7270ba095bd691660d961dcfa731141633d3bb597d0b47d69ed17e891ef884a36d4c232885097e45b41d3d3ac79dbeae6ee2282"
hostdeps="${OS_TCDEP}"
deps="core-libs"

prepare() {
	autotools_recursive_regen
}

configure() {
	autotools_configure
}

build() {
	make -j${parallelism}
}

package() {
	make install DESTDIR="${dest_dir}"

	post_package_strip
}
