#! /bin/sh

name=libatomic
skip_pkg_check=yes
version="$(. "${base_dir}/source-recipes/gcc-host" && echo ${version})"
revision=1
hostdeps="toolchain-gcc pkg-config"
imagedeps="build-essential"
deps="mlibc libgcc libstdc++"

build() {
	cd "${build_dir}"/host-builds/toolchain-gcc/build

	make -j${parallelism} all-target-libatomic
}

package() {
	cd "${build_dir}"/host-builds/toolchain-gcc/build

	rm -rf tmp_libatomic_dir
	mkdir tmp_libatomic_dir

	DESTDIR="$(realpath tmp_libatomic_dir)" make install-target-libatomic

	mkdir -p "${dest_dir}${prefix}"

	cp -r tmp_libatomic_dir/usr/local/${OS_TRIPLET}/* "${dest_dir}${prefix}"/

	# Copy libatomic into GCC's tree else it will complain.
	mkdir -p "${build_dir}"/host-pkgs/toolchain-gcc/usr/local/${OS_TRIPLET}
	cp -r tmp_libatomic_dir/usr/local/${OS_TRIPLET}/* "${build_dir}"/host-pkgs/toolchain-gcc/usr/local/${OS_TRIPLET}/
}
