#! /bin/sh
# host-recipes/clang

name=clang
revision=1
from_source="llvm"
imagedeps="build-essential"
clean_workdirs=no
repology_id=llvm
deps="mlibc-headers"

configure() {
	cmake \
	-GNinja \
	-DCMAKE_INSTALL_PREFIX=${prefix} \
	-DCMAKE_COLOR_DIAGNOSTICS=ON \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_TARGETS_TO_BUILD=X86 \
	-DLLVM_ENABLE_PROJECTS="lld;clang" \
	-DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" \
	-DLLVM_LINK_LLVM_DYLIB=ON \
	-DLLVM_ENABLE_EH=ON \
	-DLLVM_ENABLE_RTTI=ON \
	-DLLVM_INCLUDE_TESTS=OFF \
  	-DLLVM_INCLUDE_BENCHMARKS=OFF \
  	-DLLVM_INCLUDE_DOCS=OFF \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DENABLE_LINKER_BUILD_ID=ON \
	${source_dir}/llvm
}

build() {
	ninja -j${parallelism}
}

package() {
	DESTDIR="${dest_dir}" ninja install
}
