#! /bin/sh

name=limine
from_source="limine"
revision=1
imagedeps="build-essential nasm mtools"
hostdeps="toolchain-gcc pkg-config"

configure() {
	if [ "${JINX_ARCH}" = "x86_64" ]; then
		EXTRA_FLAGS="--enable-bios \
			     --enable-bios-cd \
			     --enable-bios-pxe \
			     --enable-uefi-ia32 \
		"
	fi

		CFLAGS="$HOST_CFLAGS" \
		CXXFLAGS="$HOST_CXXFLAGS" \
		LDFLAGS="$HOST_LDFLAGS -static" \
	"${source_dir}"/configure \
		--prefix="${prefix}" \
		TOOLCHAIN_FOR_TARGET=${OS_TRIPLET}- \
		$EXTRA_FLAGS \
		--enable-uefi-${JINX_ARCH} \
		--enable-uefi-cd
}

build() {
	make -j${parallelism}
}

package() {
	DESTDIR="${dest_dir}" make install

		strip_command=strip \
	post_package_strip
}
