#! /bin/sh

name=toolchain-kernel-gcc
from_source=gcc
clean_workdirs=no
revision=1
imagedeps="build-essential"
hostdeps="pkg-config"
hostrundeps="binutils-kernel"
deps="mlibc-headers"

configure() {
	"${source_dir}"/configure \
		--prefix="${prefix}" \
		--target="${OS_KERNEL_TRIPLET}" \
		--with-sysroot="${sysroot_dir}" \
		--disable-nls \
		--enable-shared \
		--enable-host-shared \
		--enable-host-bind-now \
		--disable-multilib \
		--enable-initfini-array \
		--disable-bootstrap \
		--enable-languages=c,c++,lto \
		--enable-default-pie \
		--enable-default-ssp \
		--disable-werror \
		--enable-__cxa_atexit \
		--enable-linker-build-id \
		--with-linker-hash-style=gnu
}

build() {
	make -j${parallelism} all-gcc
}

package() {
	DESTDIR="${dest_dir}" make install-gcc

		strip_command="strip" \
	post_package_strip
}
